chore: sync gradle and pipelines with api-cp-piloting-pathfinder

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -25,55 +25,55 @@ jobs:
         language: [ 'java' ]
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v5
+      - name: Checkout repository
+        uses: actions/checkout@v6
 
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v4
-      # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
-      # queries: security-extended,security-and-quality
-      with:
-        languages: ${{ matrix.language }}
-        queries: security-extended
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v4
+        # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+        # queries: security-extended,security-and-quality
+        with:
+          languages: ${{ matrix.language }}
+          queries: security-extended
 
 
-    - uses: actions/setup-java@v5
-      with:
-        distribution: 'temurin'
-        java-version: '21'
+      - uses: actions/setup-java@v5
+        with:
+          distribution: 'temurin'
+          java-version: '21'
 
-    - name: Set up Gradle
-      uses: gradle/actions/setup-gradle@v5
-      with:
-        gradle-version: current
+      - name: Set up Gradle
+        uses: gradle/actions/setup-gradle@v5
+        with:
+          gradle-version: current
 
-    - name: Gradle Build and Publish
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: |
-        gradle build cyclonedxBom -x test \
-          -DGITHUB_REPOSITORY=${{ github.repository }} \
-          -DGITHUB_ACTOR=${{ github.actor }} \
-          -DGITHUB_TOKEN=$GITHUB_TOKEN
+      - name: Gradle Build and Publish
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          gradle build cyclonedxBom -x test \
+            -DGITHUB_REPOSITORY=${{ github.repository }} \
+            -DGITHUB_ACTOR=${{ github.actor }} \
+            -DGITHUB_TOKEN=$GITHUB_TOKEN
 
-    # ℹ️ Command-line programs to run using the OS shell.
-    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
-    #   If the (auto)build fails above, remove it and uncomment the following three lines.
-    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.
-    - name: Perform CodeQL Analysis
-      uses: github/codeql-action/analyze@v4
-      with:
-        category: "/language:${{matrix.language}}"
+      # ℹ️ Command-line programs to run using the OS shell.
+      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
+      #   If the (auto)build fails above, remove it and uncomment the following three lines.
+      #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.
+      - name: Perform CodeQL Analysis
+        uses: github/codeql-action/analyze@v4
+        with:
+          category: "/language:${{matrix.language}}"
 
-    - name: Log generated SBOM Hash
-      run: sha256sum build/reports/bom.json || true
+      - name: Log generated SBOM Hash
+        run: sha256sum build/reports/cyclonedx/bom.json || true
 
-      # This ensures:
-      # - The SBOM is archived with the CodeQL scan output
-      # - It's available to download and inspect from the GitHub Actions UI
-    - name: Upload SBOM
-      if: always()
-      uses: actions/upload-artifact@v5
-      with:
-        name: sbom
-        path: build/reports/bom.json
+        # This ensures:
+        # - The SBOM is archived with the CodeQL scan output
+        # - It's available to download and inspect from the GitHub Actions UI
+      - name: Upload SBOM
+        if: always()
+        uses: actions/upload-artifact@v5
+        with:
+          name: sbom
+          path: build/reports/cyclonedx/bom.json
